### ISSUE TITLE
Database 연결 상수 관리...

### ISSUE THREAD

**Issue by krung2** [gimhanul/fine_dust#1]
현재 코드에 `string`형태로 적혀져있는 `database`연결문은 보안상 좋지 않아 보입니다

환경 변수를 사용하여 관리하고 `gitignore`하는 것이 좋아 보입니다
참고
https://velog.io/@jisoo1170/django-%EB%B9%84%EB%B0%80-%EA%B0%92-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

**Comment by dlatldhs** [comment]
보안상의 문제로 gitignore을 추가했습니다. 그리고 지금은 현재 develop 단계여서 나중에 production 때 config를 분리함과 동시에 환경변수로 참조할 생각입니다.
